[versions]
guava = "33.3.1-jre"
junit-jupiter = "5.11.3"
kafka-streams = "3.9.1"
kafka-clients = "3.9.1"
kafka-streams-test-utils = "3.9.1"
jackson-annotations = "2.19.4"
jackson-databind = "2.19.4"
log4j-slf4j-impl = "2.19.0"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka-clients"}
kafka-streams = { module = "org.apache.kafka:kafka-streams", version.ref = "kafka-streams"}
kafka-streams-test-utils = { module = "org.apache.kafka:kafka-streams-test-utils", version.ref = "kafka-streams-test-utils"}
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson-annotations"}
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind"}
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j-slf4j-impl"}
